---
name: 🔆 Umbraco Heartcore Issue
description: "Create issues/feature requests for our headless offering, Umbraco Heartcore"
body:
- type: textarea
  id: "description"
  attributes:
    label: "Issue description"
    description: "Write a summary of the issue you want to report."
  validations:
    required: true